Repository Automattic/crowdsignal-forms, pull requests merged in 2020-12, with the labels that each got.

#6 Fix applause count style
  client/components/applause/style.scss
Labels: enhancement

#7 Escape the redirect address to avoid XSS.
  includes/frontend/blocks/class-crowdsignal-forms-poll-block.php
Labels: bug

#9 Bump version to 1.3.4
  README.TXT
  changelog.txt
  crowdsignal-forms.php
  includes/admin/class-crowdsignal-forms-settings.php
  includes/admin/class-crowdsignal-forms-setup.php
  languages/crowdsignal-forms.pot
  package-lock.json
  package.json
Labels: enhancement

#10 Set-up NPS block framework
  assets/stylesheets/nps.scss
  client/blocks/nps/attributes.js
  client/blocks/nps/edit.js
  client/blocks/nps/index.js
  client/editor.js
  client/nps.js
  includes/frontend/blocks/class-crowdsignal-forms-nps-block.php
  includes/frontend/class-crowdsignal-forms-blocks.php
  package.json
Labels: enhancement

#13 Add popup & dialog logic for the NPS block
  assets/stylesheets/nps.scss
  client/blocks/nps/attributes.js
  client/blocks/nps/edit.js
  client/blocks/nps/sidebar.js
  client/components/dialog-wrapper/index.js
  client/components/dialog-wrapper/style.scss
  client/components/nps/index.js
  client/components/nps/style.scss
  client/nps.js
  includes/frontend/blocks/class-crowdsignal-forms-nps-block.php
Labels: enhancement

#12 Remove redirect URL feature
  client/blocks/poll/sidebar.js
  client/components/poll/index.js
Labels: security

#11 Show branding on editor
  assets/stylesheets/editor.scss
  client/blocks/applause/edit.js
  client/blocks/applause/sidebar.js
  client/blocks/poll/edit.js
  client/blocks/poll/hooks.js
  client/blocks/poll/sidebar.js
  client/blocks/vote/edit.js
  client/blocks/vote/sidebar.js
  client/components/brand-link/style.scss
  client/components/icon/warning-circle.js
  client/components/poll/footer-branding.js
  client/components/poll/style.scss
  client/components/sidebar-promote/index.js
  client/components/sidebar-promote/style.scss
  client/components/signal-warning/index.js
  client/components/signal-warning/style.scss
  client/components/vote/style.scss
  client/data/hooks/index.js
  client/data/poll/index.js
  includes/gateways/class-api-gateway.php
  includes/rest-api/controllers/class-account-controller.php
Labels: enhancement
